
ingestion:
  gnss:
    enabled: true
    source_url: ${GNSS_SOURCE_URL}
    api_key: ${GNSS_API_KEY}
  vlbi:
    enabled: true
    source_url: ${VLBI_SOURCE_URL}
    api_key: ${VLBI_API_KEY}
  pta:
    enabled: true
    source_url: ${PTA_SOURCE_URL}
    api_key: ${PTA_API_KEY}
  tai:
    enabled: true
    source_file: "data/bimp/utcrlab.all"

mesh_monitor:
  use_http: true
  interval_seconds: 60
  peers:
    - "https://google.com"
    - "https://cloudflare.com"
    - "https://github.com"
    - "https://microsoft.com"
    - "https://apple.com"
    - "https://akamai.com"
